# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/shift
spring.datasource.username=root
spring.datasource.password=omadokar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=shifting_super_secret_key_that_is_at_least_256_bits_long_for_hs256_algo
app.jwt.expiration-ms=86400000

razorpay.key.id=rzp_test_K2GJQPIpizHSUk
razorpay.key.secret=sUStbHPusJC5xzqAF5zudI8W
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shreyashkolhe56@gmail.com
spring.mail.password=1jwnlxzdkxesgetv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=shreyashkolhe56@gmail.com
app.frontend.url=http://Localhost:5173